"""
Reward claim tracking model.

Each row records one successful coin grant keyed on an idempotency_key
(SHA-256 hex generated by the game client). The unique constraint on
idempotency_key is the server-side deduplication mechanism.
"""
import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, String, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from omninet.database import Base


class RewardClaim(Base):
    """Audit log + idempotency guard for in-game coin reward events."""

    __tablename__ = "reward_claims"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    # SHA-256 hex derived from (device_key + event_type + context + time-window)
    idempotency_key: Mapped[str] = mapped_column(
        String(64), nullable=False, unique=True, index=True,
    )
    event_type: Mapped[str] = mapped_column(String(32), nullable=False)
    coins_awarded: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(),
    )

    def __repr__(self) -> str:
        return (
            f"<RewardClaim(user_id={self.user_id}, event={self.event_type}, "
            f"coins={self.coins_awarded})>"
        )
