"""
Pydantic schemas package.
"""
from omninet.schemas.user import (
    UserCreate,
    UserResponse,
    UserLogin,
    UserUpdate,
    DeviceResponse,
    VerificationRequest,
    PairingCodeResponse,
    PairingValidateRequest,
)
from omninet.schemas.module import (
    ModuleCreate,
    ModuleResponse,
    ModuleUpdate,
    ModulePublishRequest,
    ModuleListResponse,
    CategoryResponse,
    ContributorRequest,
    ContributorResponse,
)
from omninet.schemas.battle import (
    PetCreate,
    PetResponse,
    TeamCreate,
    TeamResponse,
    TeamListResponse,
    BattleResponse,
    BattleHistoryResponse,
    SeasonResponse,
    SeasonCreate,
)
from omninet.schemas.common import (
    MessageResponse,
    ErrorResponse,
    PaginatedResponse,
    SuccessResponse,
)
from omninet.schemas.shop import (
    CosmeticListItem,
    CosmeticListResponse,
    CosmeticDownloadResponse,
    GameplayListItem,
    GameplayListResponse,
    GameplayDownloadResponse,
    ItemListItem,
    ItemListResponse,
    ItemDownloadResponse,
    ModuleShopListItem,
    ModuleShopListResponse,
    ModuleDownloadResponse,
    SpecialListItem,
    SpecialListResponse,
    PurchaseRequest,
    PurchaseResponse,
    UserPurchaseItem,
    UserPurchasesResponse,
)

__all__ = [
    # User
    "UserCreate",
    "UserResponse",
    "UserLogin",
    "UserUpdate",
    "DeviceResponse",
    "VerificationRequest",
    "PairingCodeResponse",
    "PairingValidateRequest",
    # Module
    "ModuleCreate",
    "ModuleResponse",
    "ModuleUpdate",
    "ModulePublishRequest",
    "ModuleListResponse",
    "CategoryResponse",
    "ContributorRequest",
    "ContributorResponse",
    # Battle
    "PetCreate",
    "PetResponse",
    "TeamCreate",
    "TeamResponse",
    "TeamListResponse",
    "BattleResponse",
    "BattleHistoryResponse",
    "SeasonResponse",
    "SeasonCreate",
    # Common
    "MessageResponse",
    "ErrorResponse",
    "PaginatedResponse",
    "SuccessResponse",
    # Shop
    "CosmeticListItem",
    "CosmeticListResponse",
    "CosmeticDownloadResponse",
    "GameplayListItem",
    "GameplayListResponse",
    "GameplayDownloadResponse",
    "ItemListItem",
    "ItemListResponse",
    "ItemDownloadResponse",
    "ModuleShopListItem",
    "ModuleShopListResponse",
    "ModuleDownloadResponse",
    "SpecialListItem",
    "SpecialListResponse",
    "PurchaseRequest",
    "PurchaseResponse",
    "UserPurchaseItem",
    "UserPurchasesResponse",
]
